CREATE TABLE document_metadata
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    document_name VARCHAR(255),
    total_chunks  INT,
    uploaded_date TIMESTAMP,
    CONSTRAINT pk_document_metadata PRIMARY KEY (id)
);